-- 코드를 입력하세요
with CTE AS(
    SELECT S.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, SUM(S.SALES)*B.PRICE AS TOTAL_COUNT
    FROM BOOK_SALES AS S
    LEFT JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
    WHERE S.SALES_DATE LIKE('2022-01%')
    GROUP BY S.BOOK_ID
)
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.TOTAL_COUNT) AS TOTAL_SALES
FROM CTE AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC