-- 코드를 작성해주세요
WITH CTE AS(
    SELECT PARENT_ITEM_ID AS P
    FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID
)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN CTE AS C ON C.P = I.ITEM_ID
WHERE C.P IS NULL
ORDER BY I.ITEM_ID DESC