-- 코드를 작성해주세요
WITH CTE AS(
    SELECT PARENT_ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT E.ID, IFNULL(C.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN CTE AS C ON E.ID = C.PARENT_ID
ORDER BY E.ID