-- 코드를 입력하세요
WITH CTE AS(
    SELECT SALES_DATE, USER_ID, PRODUCT_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE LIKE('2022-03%')
    
    UNION
    
    SELECT SALES_DATE, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE('2022-03%')
)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM CTE
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC