-- 코드를 입력하세요
WITH CTE AS(
    SELECT C.CAR_ID, C.CAR_TYPE, ROUND((100-D.DISCOUNT_RATE)/100*C.DAILY_FEE*30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON D.CAR_TYPE = C.CAR_TYPE
    WHERE CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30'
          AND END_DATE >= '2022-11-01')
      AND C.CAR_TYPE IN ('세단', 'SUV')
      AND D.DURATION_TYPE LIKE('30%')
    )
  
SELECT CAR_ID, CAR_TYPE, FEE
FROM CTE 
WHERE FEE >= 500000
  AND FEE < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC