-- 코드를 작성해주세요
SELECT S.ID,
CASE
    WHEN S.RN <= MAX(S.RN) OVER()*0.25 THEN 'CRITICAL'
    WHEN S.RN <= MAX(S.RN) OVER()*0.5 THEN 'HIGH'
    WHEN S.RN <= MAX(S.RN) OVER()*0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT *, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
     FROM ECOLI_DATA) AS S
ORDER BY S.ID