-- 코드를 입력하세요
WITH CTE AS(
    SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, S.USER_ID
    FROM ONLINE_SALE S
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), S.USER_ID
)

SELECT S.YEAR, S.MONTH, U.GENDER, COUNT(*) AS USERS
FROM CTE AS S
JOIN USER_INFO AS U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY S.YEAR, S.MONTH, U.GENDER
ORDER BY S.YEAR ASC, S.MONTH ASC, U.GENDER ASC

# SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, S.USER_ID, ROW_NUMBER() OVER(PARTITION BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE))
# FROM ONLINE_SALE S
# GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), S.USER_ID
# ORDER BY YEAR, MONTH, USER_ID