-- 코드를 작성해주세요
SELECT COUNT(F.FISH_TYPE) AS FISH_COUNT, MAX(N.FISH_NAME) AS FISH_NAME
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N ON N.FISH_TYPE = F.FISH_TYPE
GROUP BY F.FISH_TYPE
ORDER BY FISH_COUNT DESC