-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_CTE AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.GENERATION+1
    FROM ECOLI_DATA AS E
    JOIN ECOLI_CTE AS C ON E.PARENT_ID = C.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_CTE
WHERE ID NOT IN(SELECT PARENT_ID FROM ECOLI_CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY 2 ASC