-- 코드를 입력하세요
SELECT C.CAR_ID, MAX(C.A) AS AVAILABILITY
FROM (SELECT *,
CASE
    WHEN TIMESTAMPDIFF(DAY, START_DATE, '2022-10-16') >= 0 
        AND TIMESTAMPDIFF(DAY, '2022-10-16', END_DATE) >= 0 
        THEN '대여중'
    ELSE '대여 가능'
END AS A
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC