-- 코드를 입력하세요

WITH CTE AS(SELECT H.HISTORY_ID, C.CAR_TYPE, TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 AS DURATION, C.DAILY_FEE, P.DURATION_TYPE, P.DISCOUNT_RATE, C.DAILY_FEE*(TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1) AS ORIGINAL_FEE,
CASE
    WHEN P.DURATION_TYPE > TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 THEN NULL
    ELSE FLOOR(C.DAILY_FEE*(100-P.DISCOUNT_RATE)/100)*(TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1)
END AS BOOL
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭')

SELECT HISTORY_ID,
CASE
    WHEN MIN(BOOL) IS NULL THEN ORIGINAL_FEE
    ELSE MIN(BOOL)
END AS FEE
FROM CTE
GROUP BY HISTORY_ID
ORDER BY 2 DESC, 1 DESC
