-- 코드를 입력하세요
WITH CTE AS(
    SELECT *, SUM(TOTAL_ORDER) AS FL_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT IFNULL(F.FLAVOR, J.FLAVOR) AS FLAVOR
FROM FIRST_HALF AS F
LEFT JOIN CTE AS J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.FL_TOTAL_ORDER DESC LIMIT 3