-- 코드를 입력하세요
WITH CTE AS(
    SELECT A.APNT_NO, A.APNT_YMD, A.PT_NO, A.MCDP_CD, A.MDDR_ID, P.PT_NAME
    FROM APPOINTMENT AS A
    LEFT JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
    WHERE A.APNT_YMD LIKE('%2022-04-13%')
      AND A.MCDP_CD = 'CS'
      AND A.APNT_CNCL_YN = 'N'
)

SELECT A.APNT_NO, A.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM CTE AS A
LEFT JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC