-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1 FROM CTE WHERE hour < 23
)

SELECT C.HOUR AS HOUR,
CASE
    WHEN O.ANIMAL_ID IS NULL THEN 0
    ELSE COUNT(*)
END AS COUNT
FROM CTE AS C
LEFT JOIN ANIMAL_OUTS AS O ON C.HOUR = HOUR(O.DATETIME)
GROUP BY C.HOUR
ORDER BY HOUR