-- 코드를 작성해주세요
WITH CTE AS(
SELECT SUM(CODE) AS CODE
FROM SKILLCODES
WHERE CATEGORY LIKE('%Front%')
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
JOIN CTE AS C ON D.SKILL_CODE & C.CODE > 0
ORDER BY ID