-- 코드를 작성해주세요
WITH CTE AS(
SELECT G.EMP_NO, E.EMP_NAME, E.SAL,
CASE
    WHEN AVG(G.SCORE) >= 96 THEN 'S'
    WHEN AVG(G.SCORE) >= 90 THEN 'A'
    WHEN AVG(G.SCORE) >= 80 THEN 'B'
    ELSE 'C'
END AS GRADE
FROM HR_GRADE AS G
LEFT JOIN HR_EMPLOYEES AS E ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE, 
CASE
    WHEN GRADE = 'S' THEN SAL*0.2
    WHEN GRADE = 'A' THEN SAL*0.15
    WHEN GRADE = 'B' THEN SAL*0.1
    ELSE SAL*0
END AS BONUS
FROM CTE
ORDER BY EMP_NO ASC