-- 코드를 입력하세요
WITH CTE AS(
    SELECT *, COUNT(*) OVER(PARTITION BY MEMBER_ID) AS R_COUNT
    FROM REST_REVIEW
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM CTE AS R
LEFT JOIN MEMBER_PROFILE AS M ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.R_COUNT = (SELECT MAX(R_COUNT) FROM CTE)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC