-- 코드를 작성해주세요
WITH CTE_ITEM AS(
    SELECT T.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
)
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM CTE_ITEM AS C
JOIN ITEM_INFO AS I ON C.ITEM_ID = I.ITEM_ID
ORDER BY ITEM_ID DESC