-- 코드를 작성해주세요
WITH CTE_ECOLI_DATA AS(
    SELECT ID AS P_ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
)
SELECT E.ID, E.GENOTYPE, CTE.PARENT_GENOTYPE
FROM ECOLI_DATA AS E
JOIN CTE_ECOLI_DATA AS CTE ON E.PARENT_ID = CTE.P_ID
WHERE E.GENOTYPE & CTE.PARENT_GENOTYPE = CTE.PARENT_GENOTYPE
ORDER BY ID ASC
