-- 코드를 작성해주세요
WITH CTE_ECOLI AS(
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS Y
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (M.MAX_SIZE-E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN CTE_ECOLI M ON YEAR(E.DIFFERENTIATION_DATE) = M.Y
ORDER BY YEAR ASC, YEAR_DEV ASC