-- 코드를 작성해주세요
WITH CTE AS(
    SELECT *, ROW_NUMBER() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM FISH_INFO
)

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM CTE AS I
LEFT JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.RN = 1
ORDER BY I.ID ASC