-- 코드를 작성해주세요
SELECT DEPT_ID, (SELECT D.DEPT_NAME_EN FROM HR_DEPARTMENT D WHERE D.DEPT_ID = E.DEPT_ID) AS DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES E
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC
