-- 코드를 작성해주세요
WITH CTE AS(
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH, AVG(LENGTH) OVER(PARTITION BY FISH_TYPE) AS AVG_LENGTH
    FROM FISH_INFO
)
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM CTE
WHERE AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC