-- 코드를 작성해주세요
WITH CTE AS(
SELECT *, CASE
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') != 0
      AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'FRONT END') != 0 THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0 THEN 'B'
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'FRONT END') != 0 THEN 'C'
    ELSE NULL
END AS GRADE
FROM DEVELOPERS
)

SELECT GRADE, ID, EMAIL
FROM CTE
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC